---
title: "clickbait_vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Clickbait Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidymodels)
library(tidyverse)
library(bestglm)
library(textclassificationexamples)
```

# Simple Logistic Regression 

```{r}
data(headlines_train)

# CREATE FEATURES ------------------------------------------------------------------------

clickbait_train <- headlines_train |>
  na.omit() |>
  mutate(
    clickbait = as.factor(clickbait),
    common = as.factor(has_common_phrase(title)),
    exaggerated = as.factor(has_exaggerated_phrase(title)), 
    num_contractions = num_contractions(title),
    #num_stop_words = num_stop_words(title),
    num_words = num_words(title),
    num_pronouns = num_pronouns(title),
    #positivity = positivity(title),
    starts_num = as.factor(starts_with_num(title)), 
    question = as.factor(has_question_word(title))
  ) |>
  select(-c(ids, title))

clickbait_test <- headlines_test |>
  na.omit() |>
  mutate(
    clickbait = as.factor(clickbait),
    common = as.factor(has_common_phrase(title)),
    exaggerated = as.factor(has_exaggerated_phrase(title)), 
    num_contractions = num_contractions(title),
    #num_stop_words = num_stop_words(title),
    num_words = num_words(title),
    num_pronouns = num_pronouns(title),
    #positivity = positivity(title),
    starts_num = as.factor(starts_with_num(title)), 
    question = as.factor(has_question_word(title))
  ) |>
  select(-c(ids, title))

# NULL MODEL -----------------------------------------------------------------------------

table(clickbait_train$clickbait)

mean(clickbait_train$clickbait == "FALSE")
```

```{r}
# MODEL SELECTION ------------------------------------------------------------------------

full_model <- glm(
  clickbait ~ common + exaggerated + num_contractions + num_words + num_pronouns + 
    starts_num + question, 
  data = clickbait_train, 
  family = binomial
  )

MASS::stepAIC(full_model, direction = "backward")

# LOGISTIC REGRESSION --------------------------------------------------------------------

simple_logistic_model<- logistic_reg() %>%
        set_engine("glm") %>%
        set_mode("classification") %>%
        fit(clickbait ~ ., data = clickbait_train)

tidy(simple_logistic_model)  

# PREDICTION and METRICS -----------------------------------------------------------------

pred_class <- predict(
  simple_logistic_model, 
  new_data = clickbait_test, 
  type = "class"
)

pred_prob <- predict(
  simple_logistic_model, 
  new_data = clickbait_test, 
  type = "prob"
)

clickbait_results <- clickbait_test |>
  select(clickbait) |>
  bind_cols(pred_class, pred_prob)

confusion_matrix <- yardstick::conf_mat(
  clickbait_results, truth = clickbait, estimate = .pred_class
  )

confusion_matrix

accuracy <- yardstick::accuracy(
  clickbait_results, truth = clickbait, estimate = .pred_class
  )

sensitivity <- yardstick::sens(
  clickbait_results, truth = clickbait, estimate = .pred_class
)

specificity <- yardstick::spec(
  clickbait_results, truth = clickbait, estimate = .pred_class
)

yardstick::roc_curve(
  clickbait_results, truth = clickbait, estimate = .pred_TRUE
) |>
  autoplot()
```

# Decision Tree 

```{r}
dec_tree <- decision_tree(tree_depth = 10) |>
  set_engine("rpart") |>
  set_mode("classification") |> 
  fit(clickbait ~ ., data = clickbait_train)

rpart.plot::rpart.plot(dec_tree$fit)
```

```{r}
# training accuracy 

augment(dec_tree, new_data = clickbait_train) |> 
  accuracy(truth = clickbait, estimate = .pred_class)

# testing accuracy 

augment(dec_tree, new_data = clickbait_test) |> 
  accuracy(truth = clickbait, estimate = .pred_class)
```



